baseURL = 'https://mill2994.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = "ananke"
publishDir = "docs"

[params]
    background_color_class = "bg-navy"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/mill2994"